name: Rust CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check
        run: cargo check --verbose
      # You can add cargo test here later
      # - name: Run tests
      #   run: cargo test --verbose
